// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB54Uz8WJWYnLy7ovMwZkeOiGglK-Td67U',
    appId: '1:1048827407544:web:YOUR_WEB_APP_ID',
    messagingSenderId: '1048827407544',
    projectId: 'fortguard-9bba5',
    authDomain: 'fortguard-9bba5.firebaseapp.com',
    storageBucket: 'fortguard-9bba5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCISoHLLNxrzvzfyhBXAobqCw28Jkcwcio',
    appId: '1:681753776306:android:d16cfec9ba3ef3b2ac39ab',
    messagingSenderId: '681753776306',
    projectId: 'fortguards-prod',
    storageBucket: 'fortguards-prod.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIY1L2uq2STJSZ9bpmYP83gtuZKgzmnLI',
    appId: '1:681753776306:ios:61bee8f1767f9daeac39ab',
    messagingSenderId: '681753776306',
    projectId: 'fortguards-prod',
    storageBucket: 'fortguards-prod.firebasestorage.app',
    iosBundleId: 'com.fortguards.app',
  );
}
